# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Resurrect Bio
email: info@resurrect.bio

description: Resurrect Bio is a plant biotech start-up, based in London. We will improve the immune system of crop species.
site-image: /assets/images/preview.jpg

url: "" # the base hostname & protocol for your site, e.g. http://example.com

twitter_username: 

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed


url: https://resurrect.bio  # the base hostname and protocol for your site, e.g. http://example.com
baseurl:  # place folder name if the site is served in a subfolder

sass:
  sass_dir: assets/css